# Generated by Django 3.1.8 on 2021-04-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210420_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zip',
            field=models.CharField(default='foobar', max_length=255),
        ),
    ]
